version: '3.8'

services:
  trader_bot:
    image: trader_bot_image
    restart: always
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    depends_on:
      - redis
      - postgres

  monitor_bot:
    image: monitor_bot_image
    restart: always
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    depends_on:
      - redis
      - postgres

  analyzer_bot:
    image: analyzer_bot_image
    restart: always
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    depends_on:
      - redis
      - postgres

  executor_bot:
    image: executor_bot_image
    restart: always
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    restart: always

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=trading_system_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
